version: '3.5'

services:
  db_auth:
    container_name: db_auth
    ports:
      - '5438:5432'
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - PGPORT=5432
      - POSTGRES_DB=db_auth
    image: postgres:16.2-alpine
